package configstore

import (
	"fmt"
	"testing"
)

func TestGetSectionNameFromLsHint(t *testing.T) {
	sourceCode := []byte(`
from factory.factory_interface import Factory
from jobs.extractors.extract_json_job import ExtractJsonJob

# ls-hint-section_name: extract_csv

class ExtractorFactory(Factory):
	def __init__(self):
		super().__init__()

	def create(self, mode, **kwargs):
		merged_config = self.get_config(mode)

		#Autogenerated File Section. Do not Edit this file

		match mode:
			case "extract_json":
				return ExtractJsonJob(config=merged_config)
			case "extract_harish":
				return ExtractJsonJob(config=merged_config)
			case "extract_girish":
				return ExtractJsonJob(config=merged_config)
			case _:
				raise ValueError("Invalid extract type")
`)

	value, err := GetSectionNameFromLsHint(sourceCode)
	fmt.Println(value)
	if err != nil {
		fmt.Println(err)
	}
}
